### ISSUE TITLE
Bug with git rebase and squash workflow

### ISSUE THREAD

**Issue by ambernormand** [OWASP/SEDATED#13]
This bug is with the github workflow using git rebase and squash functionality. Below are steps to reproduce and an example of the feedback script.

Steps to reproduce:
1. commit a secret
2. commit the removal of a secret and a small change
3. `git rebase -i`
4. update to pick the first commit and squash any prior commits
>   pick 33279343 password
>   s 6061311b remove pw and add line
5. git commit -am "No longer a password in the current code but one of the commits that was squashed included a password"
6. git push

Issue with the feedback following the push
1. Blocks the commit - should it? is there a trace of the secret within the commit history still?
2. Lists that there are "NONE" violations and shows "Good Job!" & "Push ACCEPTED" but 

>   remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
>   remote:   ___ ___ ___   _ _____ ___ ___
>   remote:  / __| __|   \ / \_   _| __|   \ SM
>   remote:  \__ \ _|| |) / A \| | | _|| |) |
>   remote:  |___/___|___/_/ \_\_| |___|___/
>   remote:  https://github.com/owasp/sedated
>   remote:
>   remote: Repo Name = git-org/my-repo
>   remote: ========================================
>   remote: ***Commits scanned (1 total):
>   remote: ee72c67be2b6682b30d2872064cbbea2d59123aa
>   remote: ========================================
>   remote: Violations listed, by line, below (results may be obfuscated):
>   remote: NONE
>   remote:       .--._____.--.
>   remote:       ( /_.) (._\ )
>   remote:   __   |  / o \  |   __
>   remote:  (oo\   \ \_-_/ /   /oo)
>   remote:   \  \__/       \__/  /
>   remote:    \   /         \   /
>   remote: Good job! No sensitive data found in your commit(s)!
>   remote: Push ACCEPTED
>   remote: ========================================
>   remote: 60 ms
>   remote: error: GH006: Protected branch update failed for refs/heads/master.
>   remote: error: Required status check "continuous-integration/drone/pr" is expected. At least 1 approving review is required by reviewers with write access.
>   To github.com:git-org/my-repo.git
>    ! [remote rejected]   master -> master (protected branch hook declined)
>   error: failed to push some refs to 'git@github.com:git-org/my-repo.git'

**Comment by sclouts** [comment]
@ambernormand sorry we haven't gotten back to you yet on this one. I see you closed the issue, were you able to resolve it, what were the steps? Let us know either way, thanks!

**Comment by ambernormand** [comment]
@SimeonCloutier Yes! We were retesting and found that we weren't able to reproduce. Looking at the feedback we must have been pushing to a protect master branch. We're all good with this and see it working as expected now!
